# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Milestone

# Model Form Field configuration
form: $/delphinium/blossom/models/milestone/fields.yaml

# Model Class name
modelClass: Delphinium\Blossom\Models\Milestone

# Default redirect location
defaultRedirect: delphinium/blossom/milestone

# Create page
create:
    title: Create Milestone
    redirect: delphinium/blossom/milestone/update/:id
    redirectClose: delphinium/blossom/milestone

# Update page
update:
    title: Edit Milestone
    redirect: delphinium/blossom/milestone
    redirectClose: delphinium/blossom/milestone

# Preview page
preview:
    title: Preview Milestone