# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Bonus

# Model Form Field configuration
form: $/delphinium/vanilla/models/bonus/fields.yaml

# Model Class name
modelClass: Delphinium\Vanilla\Models\Bonus

# Default redirect location
defaultRedirect: delphinium/vanilla/bonus

# Create page
create:
    title: Create Bonus
    redirect: delphinium/vanilla/bonus/update/:id
    redirectClose: delphinium/vanilla/bonus

# Update page
update:
    title: Edit Bonus
    redirect: delphinium/vanilla/bonus
    redirectClose: delphinium/vanilla/bonus

# Preview page
preview:
    title: Preview Bonus