# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Blossom

# Model Form Field configuration
form: $/delphinium/blossom/models/configuration/fields.yaml

# Model Class name
modelClass: Delphinium\Blossom\Models\Configuration

# Default redirect location
defaultRedirect: delphinium/blossom/configuration

# Create page
create:
    title: Create Instance
    redirect: delphinium/blossom/configuration/update/:id
    redirectClose: delphinium/blossom/configuration

# Update page
update:
    title: Edit Instance
    redirect: delphinium/blossom/configuration
    redirectClose: delphinium/blossom/configuration