# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: O Auth

# Model Form Field configuration
form: $/delphinium/redwood/models/oauth/fields.yaml

# Model Class name
modelClass: Delphinium\Redwood\Models\OAuth

# Default redirect location
defaultRedirect: delphinium/redwood/oauth

# Create page
create:
    title: Create O Auth
    redirect: delphinium/redwood/oauth/update/:id
    redirectClose: delphinium/redwood/oauth

# Update page
update:
    title: Edit O Auth
    redirect: delphinium/redwood/oauth
    redirectClose: delphinium/redwood/oauth

# Preview page
preview:
    title: Preview O Auth